/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author MINHDAT
 */
public class FrmMain extends javax.swing.JFrame {
    private FrmMain _this;
    private PnlMenu pnlMenu;
    private CustomTabbedPane tabbedPane;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initProperties();
        initComponents();
        initMyComponent();
        addEvents();
    }
    
    public void initProperties() {
        this._this = this;
        pnlMenu = new PnlMenu();
        tabbedPane = new CustomTabbedPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlContainer.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContainer, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initMyComponent() {
        pnlContainer.add(pnlMenu, BorderLayout.NORTH);
        pnlContainer.add(tabbedPane, BorderLayout.CENTER);
    }
    
//    Thêm các sự kiện
    public void addEvents() {
        pnlMenu.getBtnCreateKeys().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnCreateKeys().getName(), new PnlCreateKeys(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnCreateKeys().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnEncryption().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnEncryption().getName(), new PnlEncryption());
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnEncryption().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
         
         pnlMenu.getBtnDecryption().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnDecryption().getName(), new PnlDecryption());
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnDecryption().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnSign().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnSign().getName(), new PnlSignature());
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnSign().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnSignValidate().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnSignValidate().getName(), new PnlValidateSign());
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnSignValidate().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
