/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author MINHDAT
 */
public class FrmMain extends javax.swing.JFrame {
    private FrmMain _this;
    private PnlMenu pnlMenu;
    private CustomTabbedPane tabbedPane;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initProperties();
        initComponents();
        initMyComponent();
        addEvents();
    }
    
    public void initProperties() {
        this._this = this;
        pnlMenu = new PnlMenu();
        tabbedPane = new CustomTabbedPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ mật mã nâng cao RSA");
        setIconImage(new ImageIcon(getClass().getResource("/img/logoRSA.png").getPath()).getImage()
        );
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlContainer.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContainer, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initMyComponent() {
        pnlContainer.add(pnlMenu, BorderLayout.NORTH);
        pnlContainer.add(tabbedPane, BorderLayout.CENTER);
    }
    
//    Thêm các sự kiện
    public void addEvents() {
        pnlMenu.getBtnCreateKeys().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnCreateKeys().getName(), new PnlCreateKeys(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnCreateKeys().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnEncryption().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnEncryption().getName(), new PnlEncryption(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnEncryption().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
         
         pnlMenu.getBtnDecryption().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnDecryption().getName(), new PnlDecryption(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnDecryption().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnSign().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnSign().getName(), new PnlSignature(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnSign().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
        
        pnlMenu.getBtnSignValidate().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.addTab(pnlMenu.getBtnSignValidate().getName(), new PnlCheckSignedText(_this));
                tabbedPane.setTitleAt(tabbedPane.getTabCount()-1, pnlMenu.getBtnSignValidate().getName());
                tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
