/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MINHDAT
 */
public class PnlCreateKeys extends javax.swing.JPanel {
    private Clipboard clipboard;
    private PnlCreateKeys _this;
    private FrmMain frmMain;

    /**
     * Creates new form PnlCreateKeys
     */
    public PnlCreateKeys(FrmMain frmMain) {
        initProperties(frmMain);
        initComponents();
    }
    
    public void initProperties(FrmMain frmMain) {
        this._this = this;
        this.frmMain = frmMain;
        clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreateKeysAutomatic = new javax.swing.JButton();
        btnCreateKeyCustom = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPKNumberE = new javax.swing.JTextField();
        btnCopyPkNumberE = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPkNumberN = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnOpenPK = new javax.swing.JButton();
        btnSavePK = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnCopyPkNumberN = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPVKNumberD = new javax.swing.JTextField();
        btnCopyPVKNumberD = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPVKNumberN = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        btnOpenPVK = new javax.swing.JButton();
        btnSavePVK = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        btnCopyPVKNumberN = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnCreateKeysAutomatic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.png"))); // NOI18N
        btnCreateKeysAutomatic.setText("Tạo key tự động");
        btnCreateKeysAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateKeysAutomaticActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateKeysAutomatic);

        btnCreateKeyCustom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        btnCreateKeyCustom.setText("Tạo key thủ công");
        btnCreateKeyCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateKeyCustomActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateKeyCustom);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 16, 0));

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publickey.png"))); // NOI18N
        jLabel4.setText("PUBLIC KEY");
        jLabel4.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel10.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Số e:");
        jPanel5.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel5.add(txtPKNumberE, java.awt.BorderLayout.CENTER);

        btnCopyPkNumberE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPkNumberE.setText("Sao chép");
        btnCopyPkNumberE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPkNumberEActionPerformed(evt);
            }
        });
        jPanel5.add(btnCopyPkNumberE, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Số n:");
        jPanel9.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        txtPkNumberN.setColumns(20);
        txtPkNumberN.setLineWrap(true);
        txtPkNumberN.setRows(5);
        txtPkNumberN.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtPkNumberN);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        btnOpenPK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenPK.setText("Mở");
        btnOpenPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPKActionPerformed(evt);
            }
        });
        jPanel7.add(btnOpenPK);

        btnSavePK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSavePK.setText("Lưu");
        btnSavePK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePKActionPerformed(evt);
            }
        });
        jPanel7.add(btnSavePK);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.BorderLayout());

        btnCopyPkNumberN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPkNumberN.setText("Sao chép");
        btnCopyPkNumberN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPkNumberNActionPerformed(evt);
            }
        });
        jPanel8.add(btnCopyPkNumberN, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/privatekey.png"))); // NOI18N
        jLabel7.setText("PRIVATE KEY");
        jLabel7.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel11.add(jLabel7, java.awt.BorderLayout.NORTH);

        jPanel12.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel3.setText("Số d:");
        jPanel13.add(jLabel3, java.awt.BorderLayout.WEST);
        jPanel13.add(txtPVKNumberD, java.awt.BorderLayout.CENTER);

        btnCopyPVKNumberD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPVKNumberD.setText("Sao chép");
        btnCopyPVKNumberD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPVKNumberDActionPerformed(evt);
            }
        });
        jPanel13.add(btnCopyPVKNumberD, java.awt.BorderLayout.EAST);

        jPanel12.add(jPanel13, java.awt.BorderLayout.NORTH);

        jPanel14.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Số n:");
        jPanel15.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel14.add(jPanel15, java.awt.BorderLayout.WEST);

        jPanel23.setLayout(new java.awt.BorderLayout());

        txtPVKNumberN.setColumns(20);
        txtPVKNumberN.setLineWrap(true);
        txtPVKNumberN.setRows(5);
        txtPVKNumberN.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPVKNumberN);

        jPanel23.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnOpenPVK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenPVK.setText("Mở");
        btnOpenPVK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPVKActionPerformed(evt);
            }
        });
        jPanel24.add(btnOpenPVK);

        btnSavePVK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSavePVK.setText("Lưu");
        btnSavePVK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePVKActionPerformed(evt);
            }
        });
        jPanel24.add(btnSavePVK);

        jPanel23.add(jPanel24, java.awt.BorderLayout.SOUTH);

        jPanel14.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel25.setLayout(new java.awt.BorderLayout());

        btnCopyPVKNumberN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPVKNumberN.setText("Sao chép");
        btnCopyPVKNumberN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPVKNumberNActionPerformed(evt);
            }
        });
        jPanel25.add(btnCopyPVKNumberN, java.awt.BorderLayout.NORTH);

        jPanel14.add(jPanel25, java.awt.BorderLayout.LINE_END);

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateKeysAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateKeysAutomaticActionPerformed
        JDialogCreateKeysAutomatic jDialogCreateKeysAutomatic = new JDialogCreateKeysAutomatic(frmMain, true, _this);
        jDialogCreateKeysAutomatic.setLocationRelativeTo(null);
        jDialogCreateKeysAutomatic.setVisible(true);
    }//GEN-LAST:event_btnCreateKeysAutomaticActionPerformed

    private void btnCreateKeyCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateKeyCustomActionPerformed
        JDialogCreateKeysCustom jDialogCreateKeysCustom = new JDialogCreateKeysCustom(frmMain, true, _this);
        jDialogCreateKeysCustom.setLocationRelativeTo(null);
        jDialogCreateKeysCustom.setVisible(true);
    }//GEN-LAST:event_btnCreateKeyCustomActionPerformed

    private void btnCopyPkNumberEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPkNumberEActionPerformed
        StringSelection selection = new StringSelection(txtPKNumberE.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPkNumberEActionPerformed

    private void btnCopyPkNumberNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPkNumberNActionPerformed
        StringSelection selection = new StringSelection(txtPkNumberN.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPkNumberNActionPerformed

    private void btnOpenPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPKActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            Đọc properties
            Properties prop = new Properties();
            try (InputStream inputStream = new FileInputStream(file);) {
                prop.load(inputStream);
                txtPKNumberE.setText(prop.getProperty("e"));
                txtPkNumberN.setText(prop.getProperty("n"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOpenPKActionPerformed

    private void btnSavePKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePKActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".properties")) {
                path += ".properties";
            }
//            Ghi dữ liệu vào file properties
            Properties prop = new Properties();
            prop.setProperty("e", txtPKNumberE.getText());
            prop.setProperty("n", txtPkNumberN.getText());
            try (OutputStream outputStream = new FileOutputStream(new File(path))) {
                prop.store(outputStream, "-------------PUBLIC KEY-------------");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSavePKActionPerformed

    private void btnCopyPVKNumberDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPVKNumberDActionPerformed
        StringSelection selection = new StringSelection(txtPVKNumberD.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPVKNumberDActionPerformed

    private void btnCopyPVKNumberNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPVKNumberNActionPerformed
        StringSelection selection = new StringSelection(txtPVKNumberN.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPVKNumberNActionPerformed

    private void btnOpenPVKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPVKActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            Đọc properties
            Properties prop = new Properties();
            try (InputStream inputStream = new FileInputStream(file);) {
                prop.load(inputStream);
                txtPVKNumberD.setText(prop.getProperty("d"));
                txtPVKNumberN.setText(prop.getProperty("n"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOpenPVKActionPerformed

    private void btnSavePVKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePVKActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".properties")) {
                path += ".properties";
            }
//            Ghi dữ liệu vào file properties
            Properties prop = new Properties();
            prop.setProperty("d", txtPVKNumberD.getText());
            prop.setProperty("n", txtPVKNumberN.getText());
            try (OutputStream outputStream = new FileOutputStream(new File(path))) {
                prop.store(outputStream, "-------------PRIVATE KEY-------------");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSavePVKActionPerformed


//    Getters and setters
    public JButton getBtnCopyPVKNumberD() {
        return btnCopyPVKNumberD;
    }

    public void setBtnCopyPVKNumberD(JButton btnCopyPVKNumberD) {
        this.btnCopyPVKNumberD = btnCopyPVKNumberD;
    }

    public JButton getBtnCopyPVKNumberN() {
        return btnCopyPVKNumberN;
    }

    public void setBtnCopyPVKNumberN(JButton btnCopyPVKNumberN) {
        this.btnCopyPVKNumberN = btnCopyPVKNumberN;
    }

    public JButton getBtnCopyPkNumberE() {
        return btnCopyPkNumberE;
    }

    public void setBtnCopyPkNumberE(JButton btnCopyPkNumberE) {
        this.btnCopyPkNumberE = btnCopyPkNumberE;
    }

    public JButton getBtnCopyPkNumberN() {
        return btnCopyPkNumberN;
    }

    public void setBtnCopyPkNumberN(JButton btnCopyPkNumberN) {
        this.btnCopyPkNumberN = btnCopyPkNumberN;
    }

    public JButton getBtnCreateKeyCustom() {
        return btnCreateKeyCustom;
    }

    public void setBtnCreateKeyCustom(JButton btnCreateKeyCustom) {
        this.btnCreateKeyCustom = btnCreateKeyCustom;
    }

    public JButton getBtnCreateKeysAutomatic() {
        return btnCreateKeysAutomatic;
    }

    public void setBtnCreateKeysAutomatic(JButton btnCreateKeysAutomatic) {
        this.btnCreateKeysAutomatic = btnCreateKeysAutomatic;
    }

    public JButton getBtnOpenPK() {
        return btnOpenPK;
    }

    public void setBtnOpenPK(JButton btnOpenPK) {
        this.btnOpenPK = btnOpenPK;
    }

    public JButton getBtnOpenPVK() {
        return btnOpenPVK;
    }

    public void setBtnOpenPVK(JButton btnOpenPVK) {
        this.btnOpenPVK = btnOpenPVK;
    }

    public JButton getBtnSavePK() {
        return btnSavePK;
    }

    public void setBtnSavePK(JButton btnSavePK) {
        this.btnSavePK = btnSavePK;
    }

    public JButton getBtnSavePVK() {
        return btnSavePVK;
    }

    public void setBtnSavePVK(JButton btnSavePVK) {
        this.btnSavePVK = btnSavePVK;
    }

    public JTextField getTxtPKNumberE() {
        return txtPKNumberE;
    }

    public void setTxtPKNumberE(JTextField txtPKNumberE) {
        this.txtPKNumberE = txtPKNumberE;
    }

    public JTextField getTxtPVKNumberD() {
        return txtPVKNumberD;
    }

    public void setTxtPVKNumberD(JTextField txtPVKNumberD) {
        this.txtPVKNumberD = txtPVKNumberD;
    }

    public JTextArea getTxtPVKNumberN() {
        return txtPVKNumberN;
    }

    public void setTxtPVKNumberN(JTextArea txtPVKNumberN) {
        this.txtPVKNumberN = txtPVKNumberN;
    }

    public JTextArea getTxtPkNumberN() {
        return txtPkNumberN;
    }

    public void setTxtPkNumberN(JTextArea txtPkNumberN) {
        this.txtPkNumberN = txtPkNumberN;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopyPVKNumberD;
    private javax.swing.JButton btnCopyPVKNumberN;
    private javax.swing.JButton btnCopyPkNumberE;
    private javax.swing.JButton btnCopyPkNumberN;
    private javax.swing.JButton btnCreateKeyCustom;
    private javax.swing.JButton btnCreateKeysAutomatic;
    private javax.swing.JButton btnOpenPK;
    private javax.swing.JButton btnOpenPVK;
    private javax.swing.JButton btnSavePK;
    private javax.swing.JButton btnSavePVK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtPKNumberE;
    private javax.swing.JTextField txtPVKNumberD;
    private javax.swing.JTextArea txtPVKNumberN;
    private javax.swing.JTextArea txtPkNumberN;
    // End of variables declaration//GEN-END:variables
}
