/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author MINHDAT
 */
public class PnlDecryption extends javax.swing.JPanel {
    private FrmMain frmMain;
    
    /**
     * Creates new form PnlCreateKeys
     */
    public PnlDecryption(FrmMain frmMain) {
        this.frmMain = frmMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPVKNumberD = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPVKNumberN = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnSelectFile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEncrypt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnOpenEncryptText = new javax.swing.JButton();
        btnSaveEncryptText = new javax.swing.JButton();
        btnCopyEncryptText = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        btnOpenPlainText = new javax.swing.JButton();
        btnSavePlainText = new javax.swing.JButton();
        btnCopyPlainText = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlain = new javax.swing.JTextArea();
        btnDecrypt = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 10));

        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel9.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Số d:");
        jPanel9.add(jLabel1, java.awt.BorderLayout.WEST);

        txtPVKNumberD.setColumns(20);
        txtPVKNumberD.setLineWrap(true);
        txtPVKNumberD.setRows(5);
        txtPVKNumberD.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtPVKNumberD);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setText("Số n:");
        jPanel13.add(jLabel2, java.awt.BorderLayout.WEST);

        txtPVKNumberN.setColumns(20);
        txtPVKNumberN.setLineWrap(true);
        txtPVKNumberN.setRows(5);
        txtPVKNumberN.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtPVKNumberN);

        jPanel13.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.CardLayout());

        btnSelectFile.setText("Chọn file");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });
        jPanel8.add(btnSelectFile, "card2");

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 16, 0));

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plaintext.png"))); // NOI18N
        jLabel4.setText("BẢNG MÃ");
        jLabel4.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel10.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        txtEncrypt.setColumns(20);
        txtEncrypt.setLineWrap(true);
        txtEncrypt.setRows(5);
        txtEncrypt.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtEncrypt);

        jPanel6.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        btnOpenEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenEncryptText.setText("Mở");
        btnOpenEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenEncryptTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnOpenEncryptText);

        btnSaveEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSaveEncryptText.setText("Lưu");
        btnSaveEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEncryptTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnSaveEncryptText);

        btnCopyEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyEncryptText.setText("Sao chép");
        btnCopyEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyEncryptTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnCopyEncryptText);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encrypt-text.png"))); // NOI18N
        jLabel7.setText("BẢNG RÕ");
        jLabel7.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel11.add(jLabel7, java.awt.BorderLayout.NORTH);

        jPanel12.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel14.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel23.setLayout(new java.awt.BorderLayout());

        btnOpenPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenPlainText.setText("Mở");
        btnOpenPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPlainTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnOpenPlainText);

        btnSavePlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSavePlainText.setText("Lưu");
        btnSavePlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlainTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnSavePlainText);

        btnCopyPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPlainText.setText("Sao chép");
        btnCopyPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPlainTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnCopyPlainText);

        jPanel23.add(jPanel24, java.awt.BorderLayout.SOUTH);

        txtPlain.setColumns(20);
        txtPlain.setLineWrap(true);
        txtPlain.setRows(5);
        txtPlain.setToolTipText("");
        txtPlain.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPlain);

        jPanel23.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        btnDecrypt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDecrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N
        btnDecrypt.setText("GIẢI MÃ");
        btnDecrypt.setPreferredSize(new java.awt.Dimension(78, 40));
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });
        add(btnDecrypt, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            Đọc properties
            Properties prop = new Properties();
            try (InputStream inputStream = new FileInputStream(file);) {
                prop.load(inputStream);
                txtPVKNumberD.setText(prop.getProperty("d"));
                txtPVKNumberN.setText(prop.getProperty("n"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnOpenEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenEncryptTextActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                    try (FileInputStream in = new FileInputStream(file);) {
                        byte[] bytes = in.readAllBytes();
                        String txt = new String(bytes);
                        txtEncrypt.setText(txt);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnOpenEncryptTextActionPerformed

    private void btnSaveEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEncryptTextActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".txt")) {
                path += ".txt";
            }
            try (FileOutputStream out = new FileOutputStream(path);) {
                byte[] bytes = txtEncrypt.getText().getBytes();
                out.write(bytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveEncryptTextActionPerformed

    private void btnCopyEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyEncryptTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtEncrypt.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyEncryptTextActionPerformed

    private void btnOpenPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPlainTextActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                    try (FileInputStream in = new FileInputStream(file);) {
                        byte[] bytes = in.readAllBytes();
                        String txt = new String(bytes);
                        txtPlain.setText(txt);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnOpenPlainTextActionPerformed

    private void btnSavePlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlainTextActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".txt")) {
                path += ".txt";
            }
            try (FileOutputStream out = new FileOutputStream(path);) {
                byte[] bytes = txtPlain.getText().getBytes();
                out.write(bytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSavePlainTextActionPerformed

    private void btnCopyPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPlainTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtPlain.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPlainTextActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        if (Validate.decrypt(this, frmMain)) {
            Key privateKey = new Key(new BigInteger(txtPVKNumberD.getText()), new BigInteger(txtPVKNumberN.getText()));
            try {
                txtPlain.setText(RSA.getDecrypt(txtEncrypt.getText(), privateKey));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

//    Getters and setters
    public JTextArea getTxtPVKNumberD() {
        return txtPVKNumberD;
    }

    public void setTxtPVKNumberD(JTextArea txtPVKNumberD) {
        this.txtPVKNumberD = txtPVKNumberD;
    }

    public JTextArea getTxtPVKNumberN() {
        return txtPVKNumberN;
    }

    public void setTxtPVKNumberN(JTextArea txtPVKNumberN) {
        this.txtPVKNumberN = txtPVKNumberN;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopyEncryptText;
    private javax.swing.JButton btnCopyPlainText;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnOpenEncryptText;
    private javax.swing.JButton btnOpenPlainText;
    private javax.swing.JButton btnSaveEncryptText;
    private javax.swing.JButton btnSavePlainText;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtEncrypt;
    private javax.swing.JTextArea txtPVKNumberD;
    private javax.swing.JTextArea txtPVKNumberN;
    private javax.swing.JTextArea txtPlain;
    // End of variables declaration//GEN-END:variables
}
