/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import org.apache.commons.io.FilenameUtils;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;

/**
 *
 * @author MINHDAT
 */
public class PnlEncryption extends javax.swing.JPanel {

    /**
     * Creates new form PnlCreateKeys
     */
    public PnlEncryption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPKNumberE = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPKNumberN = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnSelectFile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnOpenPlainText = new javax.swing.JButton();
        btnSavePlainText = new javax.swing.JButton();
        btnCopyPlainText = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlainText = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        btnOpenEncryptText = new javax.swing.JButton();
        btnSaveEncryptText = new javax.swing.JButton();
        btnCopyEncryptText = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEncryptText = new javax.swing.JTextArea();
        btnEncrypt = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 10));

        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel9.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Số e:");
        jPanel9.add(jLabel1, java.awt.BorderLayout.WEST);

        txtPKNumberE.setColumns(20);
        txtPKNumberE.setLineWrap(true);
        txtPKNumberE.setRows(5);
        txtPKNumberE.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtPKNumberE);

        jPanel9.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setText("Số n:");
        jPanel13.add(jLabel2, java.awt.BorderLayout.WEST);

        txtPKNumberN.setColumns(20);
        txtPKNumberN.setLineWrap(true);
        txtPKNumberN.setRows(5);
        txtPKNumberN.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtPKNumberN);

        jPanel13.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.CardLayout());

        btnSelectFile.setText("Chọn file");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });
        jPanel8.add(btnSelectFile, "card2");

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 16, 0));

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plaintext.png"))); // NOI18N
        jLabel4.setText("BẢNG RÕ");
        jLabel4.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel10.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel4.setLayout(new java.awt.BorderLayout());

        btnOpenPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenPlainText.setText("Mở");
        btnOpenPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnOpenPlainText);

        btnSavePlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSavePlainText.setText("Lưu");
        btnSavePlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnSavePlainText);

        btnCopyPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPlainText.setText("Sao chép");
        btnCopyPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnCopyPlainText);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        txtPlainText.setColumns(20);
        txtPlainText.setLineWrap(true);
        txtPlainText.setRows(5);
        txtPlainText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPlainText);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encrypt-text.png"))); // NOI18N
        jLabel7.setText("BẢNG MÃ");
        jLabel7.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel11.add(jLabel7, java.awt.BorderLayout.NORTH);

        jPanel12.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel14.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel23.setLayout(new java.awt.BorderLayout());

        btnOpenEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenEncryptText.setText("Mở");
        btnOpenEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenEncryptTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnOpenEncryptText);

        btnSaveEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSaveEncryptText.setText("Lưu");
        btnSaveEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEncryptTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnSaveEncryptText);

        btnCopyEncryptText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyEncryptText.setText("Sao chép");
        btnCopyEncryptText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyEncryptTextActionPerformed(evt);
            }
        });
        jPanel24.add(btnCopyEncryptText);

        jPanel23.add(jPanel24, java.awt.BorderLayout.SOUTH);

        txtEncryptText.setColumns(20);
        txtEncryptText.setLineWrap(true);
        txtEncryptText.setRows(5);
        txtEncryptText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtEncryptText);

        jPanel23.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        btnEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N
        btnEncrypt.setText("MÃ HÓA");
        btnEncrypt.setPreferredSize(new java.awt.Dimension(78, 40));
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });
        add(btnEncrypt, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            Đọc properties
            Properties prop = new Properties();
            try (InputStream inputStream = new FileInputStream(file);) {
                prop.load(inputStream);
                txtPKNumberE.setText(prop.getProperty("e"));
                txtPKNumberN.setText(prop.getProperty("n"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnOpenPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPlainTextActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                    try (FileInputStream in = new FileInputStream(file);) {
                        byte[] bytes = in.readAllBytes();
                        String txt = new String(bytes);
                        txtPlainText.setText(txt);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnOpenPlainTextActionPerformed

    private void btnSavePlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePlainTextActionPerformed

    private void btnCopyPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPlainTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtPlainText.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPlainTextActionPerformed

    private void btnOpenEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenEncryptTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenEncryptTextActionPerformed

    private void btnSaveEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEncryptTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveEncryptTextActionPerformed

    private void btnCopyEncryptTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyEncryptTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtEncryptText.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyEncryptTextActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        Key publicKey = new Key(new BigInteger(txtPKNumberE.getText()), new BigInteger(txtPKNumberN.getText()));
        try {
            txtEncryptText.setText(RSA.getEncrypt(txtPlainText.getText(), publicKey));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEncryptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopyEncryptText;
    private javax.swing.JButton btnCopyPlainText;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnOpenEncryptText;
    private javax.swing.JButton btnOpenPlainText;
    private javax.swing.JButton btnSaveEncryptText;
    private javax.swing.JButton btnSavePlainText;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea txtEncryptText;
    private javax.swing.JTextArea txtPKNumberE;
    private javax.swing.JTextArea txtPKNumberN;
    private javax.swing.JTextArea txtPlainText;
    // End of variables declaration//GEN-END:variables
}
