/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.demo_rsa;

import javax.swing.JPanel;

/**
 *
 * @author MINHDAT
 */
public class PnlMenu extends javax.swing.JPanel {
    
    /**
     * Creates new form PnlStatusBar
     */
    public PnlMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabManager = new javax.swing.JTabbedPane();
        tabCreateKeys = new javax.swing.JPanel();
        btnCreateKeys = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tabEncryptDecrypt = new javax.swing.JPanel();
        btnEncryption = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDecryption = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabSign = new javax.swing.JPanel();
        btnSign = new javax.swing.JPanel();
        btnExamRegister = new javax.swing.JLabel();
        btnSignValidate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        tabManager.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabCreateKeys.setBackground(new java.awt.Color(255, 255, 255));
        tabCreateKeys.setName("Sinh khóa"); // NOI18N
        tabCreateKeys.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnCreateKeys.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateKeys.setName("Sinh khóa"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key.png"))); // NOI18N
        jLabel20.setText("Tạo cặp khóa");
        jLabel20.setName(""); // NOI18N
        btnCreateKeys.add(jLabel20);

        tabCreateKeys.add(btnCreateKeys);

        tabManager.addTab("SINH KHÓA", tabCreateKeys);

        tabEncryptDecrypt.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        tabEncryptDecrypt.setLayout(flowLayout2);

        btnEncryption.setBackground(new java.awt.Color(255, 255, 255));
        btnEncryption.setName("Mã hóa"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encrypt.png"))); // NOI18N
        jLabel3.setText("Mã hóa");
        btnEncryption.add(jLabel3);

        tabEncryptDecrypt.add(btnEncryption);

        btnDecryption.setBackground(new java.awt.Color(255, 255, 255));
        btnDecryption.setName("Giải mã"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/decrypt.png"))); // NOI18N
        jLabel4.setText("Giải mã");
        btnDecryption.add(jLabel4);

        tabEncryptDecrypt.add(btnDecryption);

        tabManager.addTab("MÃ HÓA DỮ LIỆU", tabEncryptDecrypt);

        tabSign.setBackground(new java.awt.Color(255, 255, 255));
        tabSign.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnSign.setBackground(new java.awt.Color(255, 255, 255));
        btnSign.setName("Ký số dữ liệu"); // NOI18N

        btnExamRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnExamRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExamRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExamRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signature.png"))); // NOI18N
        btnExamRegister.setText("Ký số dữ liệu");
        btnExamRegister.setOpaque(true);
        btnSign.add(btnExamRegister);

        tabSign.add(btnSign);

        btnSignValidate.setBackground(new java.awt.Color(255, 255, 255));
        btnSignValidate.setName("Xác nhận chữ ký"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jLabel11.setText("Xác nhận chữ ký");
        btnSignValidate.add(jLabel11);

        tabSign.add(btnSignValidate);

        tabManager.addTab("CHỮ KÝ SỐ", tabSign);

        add(tabManager, "card2");
    }// </editor-fold>//GEN-END:initComponents

//    Getters and setters
    public JPanel getBtnCreateKeys() {
        return btnCreateKeys;
    }

    public void setBtnCreateKeys(JPanel btnCreateKeys) {
        this.btnCreateKeys = btnCreateKeys;
    }

    public JPanel getBtnDecryption() {
        return btnDecryption;
    }

    public void setBtnDecryption(JPanel btnDecryption) {
        this.btnDecryption = btnDecryption;
    }

    public JPanel getBtnEncryption() {
        return btnEncryption;
    }

    public void setBtnEncryption(JPanel btnEncryption) {
        this.btnEncryption = btnEncryption;
    }

    public JPanel getBtnSign() {
        return btnSign;
    }

    public void setBtnSign(JPanel btnSign) {
        this.btnSign = btnSign;
    }

    public JPanel getBtnSignValidate() {
        return btnSignValidate;
    }

    public void setBtnSignValidate(JPanel btnSignValidate) {
        this.btnSignValidate = btnSignValidate;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCreateKeys;
    private javax.swing.JPanel btnDecryption;
    private javax.swing.JPanel btnEncryption;
    private javax.swing.JLabel btnExamRegister;
    private javax.swing.JPanel btnSign;
    private javax.swing.JPanel btnSignValidate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel tabCreateKeys;
    private javax.swing.JPanel tabEncryptDecrypt;
    private javax.swing.JTabbedPane tabManager;
    private javax.swing.JPanel tabSign;
    // End of variables declaration//GEN-END:variables
}
