/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.demo_rsa;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FilenameUtils;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author MINHDAT
 */
public class PnlSignature extends javax.swing.JPanel {
    private FrmMain frmMain;

    /**
     * Creates new form PnlCreateKeys
     */
    public PnlSignature(FrmMain frmMain) {
        this.frmMain = frmMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPVKNumberD = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtPVKNumberN = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnSelectFile = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnOpenPlainText = new javax.swing.JButton();
        btnSavePlainText = new javax.swing.JButton();
        btnCopyPlainText = new javax.swing.JButton();
        scrll = new javax.swing.JScrollPane();
        txtPlainText = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        btnOpenHashCode = new javax.swing.JButton();
        btnSaveHashCode = new javax.swing.JButton();
        btnCopyHashCode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHashText = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        btnOpenSignedText = new javax.swing.JButton();
        btnSaveSignedText = new javax.swing.JButton();
        btnCopySignedText = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSignedText = new javax.swing.JTextArea();
        btnSign = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 10));

        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel9.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Số d:");
        jPanel9.add(jLabel1, java.awt.BorderLayout.WEST);

        txtPVKNumberD.setColumns(20);
        txtPVKNumberD.setLineWrap(true);
        txtPVKNumberD.setRows(5);
        txtPVKNumberD.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtPVKNumberD);

        jPanel9.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setText("Số n:");
        jPanel13.add(jLabel2, java.awt.BorderLayout.WEST);

        txtPVKNumberN.setColumns(20);
        txtPVKNumberN.setLineWrap(true);
        txtPVKNumberN.setRows(5);
        txtPVKNumberN.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txtPVKNumberN);

        jPanel13.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.CardLayout());

        btnSelectFile.setText("Chọn file");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });
        jPanel8.add(btnSelectFile, "card2");

        jPanel1.add(jPanel8, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plaintext.png"))); // NOI18N
        jLabel4.setText("BẢNG RÕ");
        jLabel4.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel10.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));
        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(10, 1, 0, 2));

        btnOpenPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenPlainText.setText("Mở");
        btnOpenPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnOpenPlainText);

        btnSavePlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSavePlainText.setText("Lưu");
        btnSavePlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnSavePlainText);

        btnCopyPlainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyPlainText.setText("Sao chép");
        btnCopyPlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyPlainTextActionPerformed(evt);
            }
        });
        jPanel7.add(btnCopyPlainText);

        jPanel4.add(jPanel7, java.awt.BorderLayout.EAST);

        txtPlainText.setColumns(20);
        txtPlainText.setLineWrap(true);
        txtPlainText.setRows(5);
        txtPlainText.setWrapStyleWord(true);
        scrll.setViewportView(txtPlainText);

        jPanel4.add(scrll, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hash.png"))); // NOI18N
        jLabel5.setText("MÃ HASH");
        jLabel5.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel11.add(jLabel5, java.awt.BorderLayout.NORTH);

        jPanel12.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.GridLayout(10, 1, 0, 2));

        btnOpenHashCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenHashCode.setText("Mở");
        btnOpenHashCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHashCodeActionPerformed(evt);
            }
        });
        jPanel16.add(btnOpenHashCode);

        btnSaveHashCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSaveHashCode.setText("Lưu");
        btnSaveHashCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHashCodeActionPerformed(evt);
            }
        });
        jPanel16.add(btnSaveHashCode);

        btnCopyHashCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopyHashCode.setText("Sao chép");
        btnCopyHashCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyHashCodeActionPerformed(evt);
            }
        });
        jPanel16.add(btnCopyHashCode);

        jPanel15.add(jPanel16, java.awt.BorderLayout.EAST);

        txtHashText.setColumns(20);
        txtHashText.setLineWrap(true);
        txtHashText.setRows(5);
        txtHashText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtHashText);

        jPanel15.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign.png"))); // NOI18N
        jLabel6.setText("CHỮ KÝ SỐ");
        jLabel6.setPreferredSize(new java.awt.Dimension(128, 60));
        jPanel17.add(jLabel6, java.awt.BorderLayout.NORTH);

        jPanel18.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel21.setLayout(new java.awt.GridLayout(10, 1, 0, 2));

        btnOpenSignedText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        btnOpenSignedText.setText("Mở");
        btnOpenSignedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenSignedTextActionPerformed(evt);
            }
        });
        jPanel21.add(btnOpenSignedText);

        btnSaveSignedText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSaveSignedText.setText("Lưu");
        btnSaveSignedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSignedTextActionPerformed(evt);
            }
        });
        jPanel21.add(btnSaveSignedText);

        btnCopySignedText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy.png"))); // NOI18N
        btnCopySignedText.setText("Sao chép");
        btnCopySignedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopySignedTextActionPerformed(evt);
            }
        });
        jPanel21.add(btnCopySignedText);

        jPanel20.add(jPanel21, java.awt.BorderLayout.EAST);

        txtSignedText.setColumns(20);
        txtSignedText.setLineWrap(true);
        txtSignedText.setRows(5);
        txtSignedText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtSignedText);

        jPanel20.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17, java.awt.BorderLayout.SOUTH);

        jScrollPane5.setViewportView(jPanel2);

        add(jScrollPane5, java.awt.BorderLayout.CENTER);

        btnSign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PEN.png"))); // NOI18N
        btnSign.setText("KÝ");
        btnSign.setPreferredSize(new java.awt.Dimension(78, 40));
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });
        add(btnSign, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Properties file", "properties");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            Đọc properties
            Properties prop = new Properties();
            try (InputStream inputStream = new FileInputStream(file);) {
                prop.load(inputStream);
                txtPVKNumberD.setText(prop.getProperty("d"));
                txtPVKNumberN.setText(prop.getProperty("n"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnOpenHashCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHashCodeActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                    try (FileInputStream in = new FileInputStream(file);) {
                        byte[] bytes = in.readAllBytes();
                        String txt = new String(bytes);
                        txtHashText.setText(txt);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnOpenHashCodeActionPerformed

    private void btnSaveHashCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHashCodeActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".txt")) {
                path += ".txt";
            }
            try (FileOutputStream out = new FileOutputStream(path);) {
                byte[] bytes = txtHashText.getText().getBytes();
                out.write(bytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveHashCodeActionPerformed

    private void btnCopyHashCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyHashCodeActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtHashText.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyHashCodeActionPerformed

    private void btnOpenSignedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenSignedTextActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                    try (FileInputStream in = new FileInputStream(file);) {
                        byte[] bytes = in.readAllBytes();
                        String txt = new String(bytes);
                        txtSignedText.setText(txt);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnOpenSignedTextActionPerformed

    private void btnSaveSignedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSignedTextActionPerformed
//        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".txt")) {
                path += ".txt";
            }
            try (FileOutputStream out = new FileOutputStream(path);) {
                byte[] bytes = txtSignedText.getText().getBytes();
                out.write(bytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveSignedTextActionPerformed

    private void btnCopySignedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopySignedTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtSignedText.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopySignedTextActionPerformed

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        if (Validate.signature(this, frmMain)) {
            try {
                String salt = BCrypt.gensalt();
                txtHashText.setText(BCrypt.hashpw(txtPlainText.getText(), salt));
                Key key = new Key(new BigInteger(txtPVKNumberD.getText()), new BigInteger(txtPVKNumberN.getText()));
                txtSignedText.setText(RSA.getEncrypt(txtHashText.getText(), key));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(frmMain, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSignActionPerformed

    private void btnCopyPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyPlainTextActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();;
        StringSelection selection = new StringSelection(txtPlainText.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_btnCopyPlainTextActionPerformed

    private void btnSavePlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlainTextActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jFileChooser.getSelectedFile().getPath();
            if (!path.endsWith(".txt")) {
                path += ".txt";
            }
            try (FileOutputStream out = new FileOutputStream(path);) {
                byte[] bytes = txtPlainText.getText().getBytes();
                out.write(bytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSavePlainTextActionPerformed

    private void btnOpenPlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPlainTextActionPerformed
        //        Tạo trình chọn file
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Txt file", "txt");
        jFileChooser.setFileFilter(fileNameExtensionFilter);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            switch (FilenameUtils.getExtension(file.getPath())) {
                case "txt":
                try (FileInputStream in = new FileInputStream(file);) {
                    byte[] bytes = in.readAllBytes();
                    String txt = new String(bytes);
                    txtPlainText.setText(txt);
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }
        }
    }//GEN-LAST:event_btnOpenPlainTextActionPerformed

//    Getters and setters
    public JTextArea getTxtPVKNumberD() {
        return txtPVKNumberD;
    }

    public void setTxtPVKNumberD(JTextArea txtPVKNumberD) {
        this.txtPVKNumberD = txtPVKNumberD;
    }

    public JTextArea getTxtPVKNumberN() {
        return txtPVKNumberN;
    }

    public void setTxtPVKNumberN(JTextArea txtPVKNumberN) {
        this.txtPVKNumberN = txtPVKNumberN;
    }

    public JTextArea getTxtPlainText() {
        return txtPlainText;
    }

    public void setTxtPlainText(JTextArea txtPlainText) {
        this.txtPlainText = txtPlainText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopyHashCode;
    private javax.swing.JButton btnCopyPlainText;
    private javax.swing.JButton btnCopySignedText;
    private javax.swing.JButton btnOpenHashCode;
    private javax.swing.JButton btnOpenPlainText;
    private javax.swing.JButton btnOpenSignedText;
    private javax.swing.JButton btnSaveHashCode;
    private javax.swing.JButton btnSavePlainText;
    private javax.swing.JButton btnSaveSignedText;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane scrll;
    private javax.swing.JTextArea txtHashText;
    private javax.swing.JTextArea txtPVKNumberD;
    private javax.swing.JTextArea txtPVKNumberN;
    private javax.swing.JTextArea txtPlainText;
    private javax.swing.JTextArea txtSignedText;
    // End of variables declaration//GEN-END:variables
}
